
name: wordle
dependencies:
- base
- text
- bytestring
- mtl
- sqlite-simple
- utility-ht
- containers
- resource-pool
- extensible
- async
- hspec

library:
  source-dirs: src

executables:
  wordle-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:  
    - wordle

tests:
  wordle-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wordle

